name: Bazel build

on: [ push ]

jobs:
  build:
    name: Run bazel
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Clang format
        shell: bash
        run: ./ci/linting/clang-format.sh

      - name: Bazel format
        shell: bash
        run: ./ci/linting/buildifier.sh

      - name: Build
        shell: bash
        run: bazel build ...

      - name: Test
        shell: bash
        run: bazel test ...
